version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  app: # The name of the service
    image: command-bus-simplified
    container_name: command-bus-simplified-app # Container name
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # Volume binding
      - ./:/app
      - /app/node_modules
    ports:
      - '4200:4200' # Port mapping